### PR TITLE
Wayland support

### PR DESCRIPTION
**Pull request by Nicky-D**
- Remove obsolete Flash code
- Add Wayland detection, start with ozone-platform=wayland if Wayland is either requested (SDL_VIDEODRIVER) or X11 is not present (no DISPLAY)

### CODE REVIEW

**Comment by Nicky-D** [comment]
@callumlinden could this PR get some love please?

**Review by callumlinden — APPROVED** [review]
Sorry for the delay.

**Review by marchcat — APPROVED** [review]
LGTM, thank you!

**Comment by marchcat** [comment]
Viewer PR: [#2243](https://github.com/secondlife/viewer/pull/2243)

**Pull request merged**
